#!/usr/bin/env python3

import optparse

from hhservice.api import models

def get_program_options(default_host='127.0.0.1',
            default_port=28015, default_dbname='test'):

    """
    Takes a flask.Flask instance and runs it. Parses 
    command-line flags to configure the app.
    """

    # Set up the command-line options
    parser = optparse.OptionParser()
    parser.add_option("-H", "--host",
                      help="Hostname of the database " + \
                           "[default %s]" % default_host,
                      default=default_host)
    parser.add_option("-P", "--port",
                      help="Port for the database " + \
                           "[default %s]" % default_port, type=int,
                      default=default_port)

    parser.add_option("-d", "--db",
            help="Port for the database " + \
            "[default %s]" % default_dbname,
            default=default_dbname)

    # parser.add_option("-D", "--debug",
    #                   action="store_true", dest="debug",
    #                   help=optparse.SUPPRESS_HELP)

    options, _ = parser.parse_args()

    return options

def main():
    options = get_program_options()
    models.init_db(**options.__dict__)

    for d in models.__all__:
        d.table_create()

if __name__ == '__main__':
    main()
